# about this theme
version: 0.0.1
themeName: Dandelion

# html lang
language: zh-cmn-Hans

# Put your favicon.ico into `hexo-site/source/` directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Dandelion Hexo Hexo-themes"

# Sidebar Avatar
# 360*360 is recommended
avatar: /img/avatar.jpg

# banner image
banner: /img/banner.jpg

# Disqus
disqus_shortname: yangfch3-blog

# Assets
css: css
js: js
images: img

# main menu navigation
menu:
  home: /
  categories: /categories
  archives: /archives
  tags: /tags
  about: /about

# stylesheets loaded in the <head>
stylesheets: 
  main: /css/main.css

# scripts loaded in the end of the body
scripts: 
  main: /js/kq.js
  lib: /js/lib/